### PR TITLE
Fix issue #18 - Use correct value of field label in multifield listing.

### PR DESCRIPTION
**Pull request by Graham-72**
The fix modifies ```function _multifield_get_usage_summary()``` by obtaining the value of the label from the relevant field.instance config file and returning it as the key of array ```$fields```.

### CODE REVIEW

**Comment by jenlampton** [comment]
I don't know that this would cause problems, but it makes me a little nervous using a user-entered string as the key of an array. 

It would be better to either modify `_multifield_get_usage_summary()` to return an array, or create a `_multifield_get_labels()` function that returns an array of labels by machine_name & instance.

**Comment by Graham-72** [comment]
Thanks @jenlampton. I have added a commit to the PR.  https://github.com/backdrop-contrib/multifield/pull/19/commits/7e16af6255dd696de36091d39592b1d810901bd3

**Review by laryn — CHANGES_REQUESTED** [review]
Can you check that whitespace in line 64?

**Comment by Graham-72** [comment]
@laryn sorry about those tabs in line 64. Hopefully corrected now.

**Pull request merged**
